export const HEX_CHAR_LIST = "0123456789abcdef"
export const FULL_CHAR_LIST = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-+=.,/:;~!@&*";
export const ALPHANUM_CHAR_LIST = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
export const ALPHANUM_UPPER_CHAR_LIST = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
export const ALPHANUM_LOWER_CHAR_LIST = "abcdefghijklmnopqrstuvwxyz0123456789";
export const NUM_CHAR_LIST = "1234567890"

export const CHAR_LIST = {
    HEX: HEX_CHAR_LIST,
    FULL: FULL_CHAR_LIST,
    ALPHANUM: ALPHANUM_CHAR_LIST,
    ALPHANUM_UPPER: ALPHANUM_UPPER_CHAR_LIST,
    ALPHANUM_LOWER: ALPHANUM_LOWER_CHAR_LIST,
    NUM: NUM_CHAR_LIST
} as const