name: CI (ts@latest)

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['20']

    name: ts@latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-version: ${{ matrix.node }}

      - name: build
        run: |
          yarn workspace rxjs add typescript@latest @types/node@latest --peer --no-save
          yarn nx compile rxjs
