blank_issues_enabled: false
contact_links:
  - name: Questions, request, issues other than Rx core bugs
    url: https://github.com/ReactiveX/rxjs/discussions
    about: For general discussions, or request please use discussions.
