codecov:
  allow_coverage_offsets: true
  notify:
    require_ci_to_pass: true
  
coverage:
  precision: 2
  round: down
  range: "100"

  status:
    project:
      default:
        enabled: yes
        threshold: 0.25%
    patch:
      default:
        enabled: yes
        target: 0%
    changes: false